In [5]:
import numpy as np

In [6]:
def cross_product(v1, v2):
    return np.cross(v1, v2)

def dot_product(v1, v2):
    return np.dot(v1, v2)

### Cross Product

In [7]:
v1 = np.array([2, 5, 6])
v2 = np.array([3, 7, 4])

In [8]:
cross_product(v1,v2)

array([-22,  10,  -1])

### Dot Product

In [11]:

A = np.array([[2, 3, 1], [4, 0, 5]]) 
B = np.array([[1, 4], [2, 3], [0, 6]]) 

In [12]:
dot_product(A,B)

array([[ 8, 23],
       [ 4, 46]])

### Eigenvaues and Eigenvectors

In [13]:
# Define the matrix A
A = np.array([[2, 1], [0, 5]])

# Compute the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues: ", eigenvalues)
print("Eigenvectors: \n", eigenvectors)


Eigenvalues:  [2. 5.]
Eigenvectors: 
 [[1.         0.31622777]
 [0.         0.9486833 ]]


In [14]:
lambda1 = eigenvalues[0]

In [15]:
lambda1

2.0

# Transformation

In [17]:
import math

v =  np.array([3,2])
T = np.array([[2,0],[0,0.5]])

In [18]:
T * v

array([[6., 0.],
       [0., 1.]])

# LU

In [20]:
import numpy as np

def lu_decomposition(matrix):
    # Check whether the matrix is invertible
    if np.linalg.det(matrix) == 0:
        raise ValueError("Matrix is not invertible.")

    # Extract elements of the matrix
    a, b = matrix[0, :]
    c, d = matrix[1, :]

    # Calculate elements of L and U
    l11, l21, l22 = 1, c / a, 1
    u11, u12, u22 = a, b, d - (c * b) / a

    # Construct the L and U matrices
    L = np.array([[l11, 0], [l21, l22]])
    U = np.array([[u11, u12], [0, u22]])

    return L, U

# Example usage
matrix = np.array([[2, 1], [8, 7]])
try:
    L, U = lu_decomposition(matrix)
    print("Matrix A:")
    print(matrix)
    print("\nLower Triangular Matrix L:")
    print(L)
    print("\nUpper Triangular Matrix U:")
    print(U)
except ValueError as e:
    print(e)


Matrix A:
[[2 1]
 [8 7]]

Lower Triangular Matrix L:
[[1. 0.]
 [4. 1.]]

Upper Triangular Matrix U:
[[2. 1.]
 [0. 3.]]
