In [36]:
import numpy as np

In [37]:
mass = [12, 20, 32]

In [38]:
volume = [ 36, 18, 10 ]

In [39]:
mvlist = [mass, volume]

In [40]:
type(mvlist)

list

In [41]:
print(mvlist)

[[12, 20, 32], [36, 18, 10]]


In [42]:
mvndarray = np.array(mvlist)

In [43]:
type(mvndarray)

numpy.ndarray

In [44]:
print(mvndarray)

[[12 20 32]
 [36 18 10]]


In [45]:
mvndarray.shape

(2, 3)

In [46]:
mvndarray[0]

array([12, 20, 32])

In [47]:
mvndarray[1]

array([36, 18, 10])

In [48]:
mvndarray[1,2]

np.int64(10)

In [49]:
mvndarray[0:2, 1:2]

array([[20],
       [18]])

In [51]:
mvndarray

array([[12, 20, 32],
       [36, 18, 10]])

In [61]:
mvndarray[0,1:3]

array([20, 32])

In [62]:
mvndarray[1,1:3]

array([18, 10])

In [63]:
mvndarray[1:2,1:3]

array([[18, 10]])